{{- if not .Values.token.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "anti-scrapling.fullname" . }}-token
  labels:
    {{- include "anti-scrapling.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  {{ .Values.token.secretKey }}: {{ randAlphaNum 32 | b64enc | quote }}
{{- end }}
