apiVersion: v1
kind: Service
metadata:
  name: {{ include "anti-scrapling.fullname" . }}
  labels:
    {{- include "anti-scrapling.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "anti-scrapling.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
    {{- if .Values.admin.enabled }}
    - name: admin
      port: {{ .Values.admin.service.port }}
      targetPort: admin
      protocol: TCP
    {{- end }}
